//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionFilter
    {
        public int Id { get; set; }
        public bool isPass { get; set; }
        public int UserInfoId { get; set; }
        public int ActionViewId { get; set; }
    
        public virtual Actionview Actionview { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
