//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aaEntities : DbContext
    {
        public aaEntities()
            : base("name=aaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionFilter> ActionFilter { get; set; }
        public virtual DbSet<Actionview> Actionview { get; set; }
        public virtual DbSet<ExamTure> ExamTure { get; set; }
        public virtual DbSet<Restult> Restult { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<UserExam> UserExam { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<Table_1> Table_1 { get; set; }
        public virtual DbSet<Table_2> Table_2 { get; set; }
    }
}
