//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restult
    {
        public int Id { get; set; }
        public System.DateTime starttime { get; set; }
        public System.DateTime endtime { get; set; }
        public int score { get; set; }
        public int UserExamId { get; set; }
    
        public virtual UserExam UserExam { get; set; }
    }
}
