//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserExam()
        {
            this.Restult = new HashSet<Restult>();
        }
    
        public int Id { get; set; }
        public string PerponID { get; set; }
        public string iphone { get; set; }
        public string name { get; set; }
        public string root { get; set; }
        public short status { get; set; }
        public string car { get; set; }
        public string sub { get; set; }
        public short DelFlag { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restult> Restult { get; set; }
    }
}
